dependencies:
  '@rush-temp/2.4-office-ui-fabric-react-test': 'file:projects/2.4-office-ui-fabric-react-test.tgz'
  '@rush-temp/2.7-office-ui-fabric-react-test': 'file:projects/2.7-office-ui-fabric-react-test.tgz'
  '@rush-temp/2.8-office-ui-fabric-react-test': 'file:projects/2.8-office-ui-fabric-react-test.tgz'
  '@rush-temp/2.9-office-ui-fabric-react-test': 'file:projects/2.9-office-ui-fabric-react-test.tgz'
  '@rush-temp/3.0-office-ui-fabric-react-test': 'file:projects/3.0-office-ui-fabric-react-test.tgz'
  '@rush-temp/3.1-office-ui-fabric-react-test': 'file:projects/3.1-office-ui-fabric-react-test.tgz'
  '@rush-temp/3.2-office-ui-fabric-react-test': 'file:projects/3.2-office-ui-fabric-react-test.tgz'
  '@rush-temp/3.3-office-ui-fabric-react-test': 'file:projects/3.3-office-ui-fabric-react-test.tgz'
  '@rush-temp/3.4-office-ui-fabric-react-test': 'file:projects/3.4-office-ui-fabric-react-test.tgz'
  '@types/node': 8.5.8
  '@types/react': 16.3.16
  '@types/react-dom': 16.0.5
  tslib: 1.9.3
  typescript: 2.4.2
packages:
  /@types/node/8.5.8:
    dev: false
    resolution:
      integrity: sha512-8KmlRxwbKZfjUHFIt3q8TF5S2B+/E5BaAoo/3mgc5h6FJzqxXkCK/VMetO+IRDtwtU6HUvovHMBn+XRj7SV9Qg==
  /@types/react-dom/16.0.5:
    dependencies:
      '@types/node': 8.5.8
      '@types/react': 16.3.16
    dev: false
    resolution:
      integrity: sha512-ony2hEYlGXCLWNAWWgbsHR7qVvDbeMRFc5b43+7dhj3n+zXzxz81HV9Yjpc3JD8vLCiwYoSLqFCI6bD0+0zG2Q==
  /@types/react/16.3.16:
    dependencies:
      csstype: 2.6.4
    dev: false
    resolution:
      integrity: sha512-fM7YX3Q9a915DXi8T06F8906bWv19sbkVO+k5PUYRIWXU2PINLEHbMMGgySem2phwF6En0+HGI6MOrobp+Ya1g==
  /csstype/2.6.4:
    dev: false
    resolution:
      integrity: sha512-lAJUJP3M6HxFXbqtGRc0iZrdyeN+WzOWeY0q/VnFzI+kqVrYIzC7bWlKqCW7oCIdzoPkvfp82EVvrTlQ8zsWQg==
  /tslib/1.9.3:
    dev: false
    resolution:
      integrity: sha512-4krF8scpejhaOgqzBEcGM7yDIEfi0/8+8zDRZhNZZ2kjmHJ4hv3zCbQWxoJGz1iw5U0Jl0nma13xzHXcncMavQ==
  /typescript/2.4.2:
    dev: false
    engines:
      node: '>=4.2.0'
    hasBin: true
    resolution:
      integrity: sha1-+DlfhdRZJ2BnyYiqQYN6j4KHCEQ=
  /typescript/2.7.2:
    dev: false
    engines:
      node: '>=4.2.0'
    hasBin: true
    resolution:
      integrity: sha512-p5TCYZDAO0m4G344hD+wx/LATebLWZNkkh2asWUFqSsD2OrDNhbAHuSjobrmsUmdzjJjEeZVU9g1h3O6vpstnw==
  /typescript/2.8.4:
    dev: false
    engines:
      node: '>=4.2.0'
    hasBin: true
    resolution:
      integrity: sha512-IIU5cN1mR5J3z9jjdESJbnxikTrEz3lzAw/D0Tf45jHpBp55nY31UkUvmVHoffCfKHTqJs3fCLPDxknQTTFegQ==
  /typescript/2.9.2:
    dev: false
    engines:
      node: '>=4.2.0'
    hasBin: true
    resolution:
      integrity: sha512-Gr4p6nFNaoufRIY4NMdpQRNmgxVIGMs4Fcu/ujdYk3nAZqk7supzBE9idmvfZIlH/Cuj//dvi+019qEue9lV0w==
  /typescript/3.0.3:
    dev: false
    engines:
      node: '>=4.2.0'
    hasBin: true
    resolution:
      integrity: sha512-kk80vLW9iGtjMnIv11qyxLqZm20UklzuR2tL0QAnDIygIUIemcZMxlMWudl9OOt76H3ntVzcTiddQ1/pAAJMYg==
  /typescript/3.1.6:
    dev: false
    engines:
      node: '>=4.2.0'
    hasBin: true
    resolution:
      integrity: sha512-tDMYfVtvpb96msS1lDX9MEdHrW4yOuZ4Kdc4Him9oU796XldPYF/t2+uKoX0BBa0hXXwDlqYQbXY5Rzjzc5hBA==
  /typescript/3.2.4:
    dev: false
    engines:
      node: '>=4.2.0'
    hasBin: true
    resolution:
      integrity: sha512-0RNDbSdEokBeEAkgNbxJ+BLwSManFy9TeXz8uW+48j/xhEXv1ePME60olyzw2XzUqUBNAYFeJadIqAgNqIACwg==
  /typescript/3.3.4000:
    dev: false
    engines:
      node: '>=4.2.0'
    hasBin: true
    resolution:
      integrity: sha512-jjOcCZvpkl2+z7JFn0yBOoLQyLoIkNZAs/fYJkUG6VKy6zLPHJGfQJYFHzibB6GJaF/8QrcECtlQ5cpvRHSMEA==
  /typescript/3.4.5:
    dev: false
    engines:
      node: '>=4.2.0'
    hasBin: true
    resolution:
      integrity: sha512-YycBxUb49UUhdNMU5aJ7z5Ej2XGmaIBL0x34vZ82fn3hGvD+bgrMrVDpatgz2f7YxUMJxMkbWxJZeAvDxVe7Vw==
  'file:projects/2.4-office-ui-fabric-react-test.tgz':
    dependencies:
      '@types/node': 8.5.8
      '@types/react': 16.3.16
      '@types/react-dom': 16.0.5
      tslib: 1.9.3
      typescript: 2.4.2
    dev: false
    name: '@rush-temp/2.4-office-ui-fabric-react-test'
    resolution:
      integrity: sha512-N03btgOXf9+/VNHv/0sf5rtNrqhcFVlDu6OFZIwGcdaIbT+FY37pIb7CHAkiTyYBC9llvNuuWgRvyTSVBECLUw==
      tarball: 'file:projects/2.4-office-ui-fabric-react-test.tgz'
    version: 0.0.0
  'file:projects/2.7-office-ui-fabric-react-test.tgz':
    dependencies:
      '@types/node': 8.5.8
      '@types/react': 16.3.16
      '@types/react-dom': 16.0.5
      tslib: 1.9.3
      typescript: 2.7.2
    dev: false
    name: '@rush-temp/2.7-office-ui-fabric-react-test'
    resolution:
      integrity: sha512-nTNLPXNM+dkOqGtnbk3OweI0bqxlBeQspUYtWu1r2JcItbewWqZDU5DqQhspVik3HxdxyZfbP4+OZD44ibipjg==
      tarball: 'file:projects/2.7-office-ui-fabric-react-test.tgz'
    version: 0.0.0
  'file:projects/2.8-office-ui-fabric-react-test.tgz':
    dependencies:
      '@types/node': 8.5.8
      '@types/react': 16.3.16
      '@types/react-dom': 16.0.5
      tslib: 1.9.3
      typescript: 2.8.4
    dev: false
    name: '@rush-temp/2.8-office-ui-fabric-react-test'
    resolution:
      integrity: sha512-mGKYMkwFOo9tfT5XdZnGs5QHa+9FQxEI37Gtt1mk+URZHD8pXnKLYn5SFY+Yh005k4aQ9InlXxTtLN6OAHvRzQ==
      tarball: 'file:projects/2.8-office-ui-fabric-react-test.tgz'
    version: 0.0.0
  'file:projects/2.9-office-ui-fabric-react-test.tgz':
    dependencies:
      '@types/node': 8.5.8
      '@types/react': 16.3.16
      '@types/react-dom': 16.0.5
      tslib: 1.9.3
      typescript: 2.9.2
    dev: false
    name: '@rush-temp/2.9-office-ui-fabric-react-test'
    resolution:
      integrity: sha512-4A914Do0OuLg0TvubgsDavxin/mDAKZx+hzyR1ASODUTkr2P5Reu6JChOwuE4YcA9taSLmNvc8BqOO2Y1n/kPQ==
      tarball: 'file:projects/2.9-office-ui-fabric-react-test.tgz'
    version: 0.0.0
  'file:projects/3.0-office-ui-fabric-react-test.tgz':
    dependencies:
      '@types/node': 8.5.8
      '@types/react': 16.3.16
      '@types/react-dom': 16.0.5
      tslib: 1.9.3
      typescript: 3.0.3
    dev: false
    name: '@rush-temp/3.0-office-ui-fabric-react-test'
    resolution:
      integrity: sha512-eIwYVvb201wZXLCGg0vACaowBSAxbCeW06+SBkvKOI8i4lnq0WEkxUuzEWwy4tbUWrauTvjEpaqzvR2EYrRtjA==
      tarball: 'file:projects/3.0-office-ui-fabric-react-test.tgz'
    version: 0.0.0
  'file:projects/3.1-office-ui-fabric-react-test.tgz':
    dependencies:
      '@types/node': 8.5.8
      '@types/react': 16.3.16
      '@types/react-dom': 16.0.5
      tslib: 1.9.3
      typescript: 3.1.6
    dev: false
    name: '@rush-temp/3.1-office-ui-fabric-react-test'
    resolution:
      integrity: sha512-Qha2GpTOQGqYXHlZraJrC8xm1lvqjrl0Jq80gcs37aRGK/7Y7fQJYteIIQWaFfsZfO1iHz1pbkXnp7KNnTxmCg==
      tarball: 'file:projects/3.1-office-ui-fabric-react-test.tgz'
    version: 0.0.0
  'file:projects/3.2-office-ui-fabric-react-test.tgz':
    dependencies:
      '@types/node': 8.5.8
      '@types/react': 16.3.16
      '@types/react-dom': 16.0.5
      tslib: 1.9.3
      typescript: 3.2.4
    dev: false
    name: '@rush-temp/3.2-office-ui-fabric-react-test'
    resolution:
      integrity: sha512-hcVK1ZHQyEbTaWUyiC4xvbfuJ9Um1043i88JNXFFarPoE0SxDPU6c4TUWi5mrIhnIKvBD590yAsqiDWvocpWiQ==
      tarball: 'file:projects/3.2-office-ui-fabric-react-test.tgz'
    version: 0.0.0
  'file:projects/3.3-office-ui-fabric-react-test.tgz':
    dependencies:
      '@types/node': 8.5.8
      '@types/react': 16.3.16
      '@types/react-dom': 16.0.5
      tslib: 1.9.3
      typescript: 3.3.4000
    dev: false
    name: '@rush-temp/3.3-office-ui-fabric-react-test'
    resolution:
      integrity: sha512-Fc8wHuEZwxO/xFashtRWSUnftP77BI5bhy1m2E1SjqG4FU7GAFe+E4Uv1xIXspYEzF9fkU/XEZfihV8L5MB7nw==
      tarball: 'file:projects/3.3-office-ui-fabric-react-test.tgz'
    version: 0.0.0
  'file:projects/3.4-office-ui-fabric-react-test.tgz':
    dependencies:
      '@types/node': 8.5.8
      '@types/react': 16.3.16
      '@types/react-dom': 16.0.5
      tslib: 1.9.3
      typescript: 3.4.5
    dev: false
    name: '@rush-temp/3.4-office-ui-fabric-react-test'
    resolution:
      integrity: sha512-TmH8vPTmQXfpQ8EjHkECBinler1B5Oz+V2c0NLLhtqp5s3OjuLvVbN35hXRqIlEYlv/s03BV/48GTIIJJlXo1w==
      tarball: 'file:projects/3.4-office-ui-fabric-react-test.tgz'
    version: 0.0.0
registry: 'https://registry.npmjs.org/'
shrinkwrapMinorVersion: 9
shrinkwrapVersion: 3
specifiers:
  '@rush-temp/2.4-office-ui-fabric-react-test': 'file:./projects/2.4-office-ui-fabric-react-test.tgz'
  '@rush-temp/2.7-office-ui-fabric-react-test': 'file:./projects/2.7-office-ui-fabric-react-test.tgz'
  '@rush-temp/2.8-office-ui-fabric-react-test': 'file:./projects/2.8-office-ui-fabric-react-test.tgz'
  '@rush-temp/2.9-office-ui-fabric-react-test': 'file:./projects/2.9-office-ui-fabric-react-test.tgz'
  '@rush-temp/3.0-office-ui-fabric-react-test': 'file:./projects/3.0-office-ui-fabric-react-test.tgz'
  '@rush-temp/3.1-office-ui-fabric-react-test': 'file:./projects/3.1-office-ui-fabric-react-test.tgz'
  '@rush-temp/3.2-office-ui-fabric-react-test': 'file:./projects/3.2-office-ui-fabric-react-test.tgz'
  '@rush-temp/3.3-office-ui-fabric-react-test': 'file:./projects/3.3-office-ui-fabric-react-test.tgz'
  '@rush-temp/3.4-office-ui-fabric-react-test': 'file:./projects/3.4-office-ui-fabric-react-test.tgz'
  '@types/node': 8.5.8
  '@types/react': 16.3.16
  '@types/react-dom': 16.0.5
  tslib: 1.9.3
  typescript: ~2.4.2
